[main][deploy] deployment script for xALPACA.
alpaca-finance/xALPACA-contract pull request #23
Opened 2021-12-07 12:32 UTC by blackalpacaa

## Description

- Create deployment script for xAlpacaa contract.

## Why?

- In order to deploy xAlpaca, Grasshouse, AlpacaFeeder to testnet or mainnet.
## ChangeLogs:

### Link to story (if available)

2021-12-08 04:09 UTC, alpanaca commented
I suggest we put a sequence of contract deployment in the readme.md

Step:
1. Deploy xAlpaca
2. Deploy proxy token
3. Deploy Grasshouse
4. Deploy Feeder

2021-12-08 11:28 UTC, alpanaca approved these changes

2021-12-09 07:54 UTC, sora-alpaca requested changes

2021-12-09 07:54 UTC, sora-alpaca commented on deploy/exec/alpaca-feeder/deploy/alpaca-feeder.ts
> +  await proxyToken.setOkHolders([alpacaFeeder.address], true);
should we add fairlaunch to be okHolders

2021-12-09 07:54 UTC, sora-alpaca commented on deploy/exec/grasshouse/config/checkpoint.ts
> +    GRASSHOUSE_ADDRESS: string;
why uppercase

2021-12-09 07:54 UTC, sora-alpaca commented on deploy/exec/proxy-token/deploy/proxy-token.ts
> +  const TIMELOCK = "0x2D5408f2287BF9F9B05404794459a846651D0a59";
should we do this as constant

2021-12-09 07:54 UTC, sora-alpaca commented on deploy/exec/xalpaca/deploy/xalpaca.ts
> +  const ALPACA_TOKEN = ""; // Address of alpaca token
constant

2021-12-13 04:53 UTC, spicysquid168 requested changes

2021-12-13 04:53 UTC, spicysquid168 commented on deploy/exec/alpaca-feeder/deploy/alpaca-feeder.ts
> +  const ALPACA_TOKEN = "";
Please move all known variables to json files instead i.e. ALPACA_TOKEN, FAIR_LAUNCH, PROXY_TOKEN

2021-12-13 04:53 UTC, spicysquid168 commented on deploy/exec/proxy-token/deploy/proxy-token.ts
> +  const TIMELOCK = ""; // Address of TIMELOCK
This is known contract, hence better read it from json file

2021-12-13 04:53 UTC, spicysquid168 commented on deploy/exec/xalpaca/deploy/xalpaca.ts
> +  const ALPACA_TOKEN = ""; // Address of alpaca token
read from json file

2021-12-14 05:44 UTC, adirutwn approved these changes

2021-12-14 05:52 UTC, spicysquid168 approved these changes

2021-12-14 05:53 UTC, sora-alpaca approved these changes

2021-12-14 05:54 UTC, merged