[wip][feat]: create alpacafeeder02 contract for supporting ftm.
alpaca-finance/xALPACA-contract pull request #48
Opened 2022-03-14 12:24 UTC by blackalpacaa

## Description

- Created contract AlpacaFeeder02 including unit test and integration test for supporting FTM chain.

## Why?

## ChangeLogs:

### Link to story (if available)

2022-03-15 05:40 UTC, alpanaca commented on contracts/8.10/mocks/MockMiniFL.sol
> +    // do nothing
Remove this

2022-03-15 05:41 UTC, alpanaca commented on tests/helpers/timelock.ts
> +import * as ftmAddresses from "../constants/bsc/addresses";
```suggestion
import * as ftmAddresses from "../constants/ftm/addresses";
```

2022-03-16 05:06 UTC, jr-alpaca commented on contracts/8.10/AlpacaFeeder02.sol
> +    require(_stakeToken == _proxyToken, "!same stakeToken");
Please use revert Error
```suggestion
    if(_stakeToken != _proxyToken) revert AlpacaFeeder02_InvalidToken();

```

2022-03-16 05:15 UTC, jr-alpaca commented on contracts/8.10/mocks/MockMiniFL.sol
> +import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";
```suggestion
import "@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol";

import "../interfaces/IMiniFL.sol";

import "../SafeToken.sol";

```

2022-03-16 07:57 UTC, sora-alpaca requested changes

2022-03-16 07:57 UTC, sora-alpaca commented on contracts/8.10/AlpacaFeeder02.sol
> +    emit LogSetNewGrassHouse(msg.sender, _prevGrassHouse, address(_newGrassHouse));
```suggestion
    emit LogSetGrassHouse(msg.sender, _prevGrassHouse, address(_newGrassHouse));
```

2022-03-16 07:57 UTC, sora-alpaca commented on contracts/8.10/AlpacaFeeder02.sol
> +  event LogSetNewGrassHouse(address indexed _caller, address _prevGrassHouse, address _newGrassHouse);
```suggestion
  event LogSetGrassHouse(address indexed _caller, address _prevGrassHouse, address _newGrassHouse);
```

2022-03-16 07:57 UTC, sora-alpaca commented on tests/helpers/deploy.ts
> +import * as addresses from "../constants/bsc/addresses";
```suggestion
import * as bscAddresses from "../constants/bsc/addresses";
```

2022-03-16 07:57 UTC, sora-alpaca commented on tests/helpers/timelock.ts
> +import * as addresses from "../constants/bsc/addresses";
```suggestion
import * as bscAddresses from "../constants/bsc/addresses";
```

2022-03-16 07:57 UTC, sora-alpaca commented on tests/unit/AlpacaFeeder02.test.ts
> +  context("#initialize", () => {
add testcase for `#setGrasshouse` function

2022-03-16 09:35 UTC, jr-alpaca approved these changes

2022-03-16 09:59 UTC, sora-alpaca requested changes

2022-03-16 09:59 UTC, sora-alpaca commented on tests/unit/AlpacaFeeder02.test.ts
> +  describe("#setGrassHouse", async () => {
1 enter

2022-03-16 10:06 UTC, sora-alpaca commented on tests/helpers/timelock.ts
> +
add TODO: uncomment if miniFL owner is timelock else remove this

2022-03-16 10:18 UTC, sora-alpaca approved these changes

2022-03-16 10:26 UTC, alpanaca approved these changes

2022-03-17 04:32 UTC, merged