[main][feat] xalpaca feeder contract
alpaca-finance/xALPACA-contract pull request #8
Opened 2021-11-09 12:21 UTC by sora-alpaca

## Description

## Why?

## ChangeLogs:

### Link to story (if available)

2021-11-10 09:24 UTC, spicysquid168 requested changes

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +import "@openzeppelin/contracts/utils/math/SafeCast.sol";
Use `contracts-upgradeable`

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +// solhint-disable-next-line contract-name-camelcase
remove this

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +import "./interfaces/IDebtToken.sol";
Rename this to `IProxyToken.sol`

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    proxyToken.mint(address(this), 1e18);
should require to prevent multiple mint & deposit to FairLaunch. As proxyToken will be owned and can only be minted by AlpacaFeeder, hence you can do `require(proxyToken.balanceOf(address(fairLaunch)), "already deposit");` to prevent.

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +  function fairLaunchDeposit() external {
Should be executed by owner only

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +  function fairLaunchWithdraw() external {
should be executed by owner only

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xcc6dbc27, fairLaunchPoolId));
doesn't need to do external call. It can just be `fairLaunch.withdraw(...)`

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xddc63262, fairLaunchPoolId));
can just do a simple call

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xddc63262, fairLaunchPoolId));
Add `LogFairLaunchHarvest(address _caller, uint256 _harvestAmount)` to log the state changes

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +  function withdraw(address _to, uint256 _amount) external onlyOwner {
Remove this. No need to `withdraw` ALPACA from this contract.

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    fairLaunch.deposit(address(this), fairLaunchPoolId, 1e18);
Add `emit LogFairLaunchDeposit()`

2021-11-10 09:24 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    if (success) proxyToken.burn(address(this), SafeToken.myBalance(address(proxyToken)));
Add `emit LogFairLaunchWithdraw()`

2021-11-10 10:06 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xddc63262, fairLaunchPoolId));
What if harvest call failed? Then feed would fail too?

2021-11-10 10:08 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xddc63262, fairLaunchPoolId));
But that would be an edge case where emission has gone to 0.

2021-11-11 05:38 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +Ported to Solidity from: https://github.com/curvefi/curve-dao-contracts/blob/master/contracts/VotingEscrow.vy
Please remove this line

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    uint256 before = token.myBalance();
_before

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    (bool success, ) = address(fairLaunch).call(abi.encodeWithSelector(0xddc63262, fairLaunchPoolId));
_success

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    if (success) emit LogFairLaunchHarvest(address(this), token.myBalance() - before);
_success , _before

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    SafeToken.safeApprove(token, address(grassHouse), token.myBalance());
token.safeApprove(address(grassHouse), token.myBalance())

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/AlpacaFeeder.sol
> +    SafeToken.safeApprove(token, address(grassHouse), 0);
token.safeApprove

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/interfaces/IFairLaunch.sol
> +  // function pendingAlpaca(uint256 _pid, address _user) external view returns (uint256);
If not used, please remove.

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/interfaces/IProxyToken.sol
> +  function mint(address to, uint256 amount) external;
_to, _amount

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/interfaces/IProxyToken.sol
> +  function burn(address from, uint256 amount) external;
_from, _amount

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/interfaces/IVault.sol
> +  // /// @dev Return the total ERC20 entitled to the token holders. Be careful of unaccrued interests.
If not used, please remove

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/mocks/MockFairLaunch.sol
> +    SafeToken.safeApprove(proxyToken, _for, _amount);
proxyToken.safeApprove

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +    for (uint256 idx = 0; idx < _okHolders.length; idx++) {
_idx

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +  function mint(address to, uint256 amount) public override onlyOwner {
_to, _amount

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +  function burn(address from, uint256 amount) public override onlyOwner {
_from, _amount

2021-11-11 05:57 UTC, alpanaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +    _burn(from, amount);
_from, _amount

2021-11-11 05:57 UTC, alpanaca commented on tests/AlpacaFeeder.test.ts
> +// import * as timeHelpers from "./helpers/time";
If not used, please remove

2021-11-11 05:57 UTC, alpanaca commented on tests/AlpacaFeeder.test.ts
> +    context("revert on deposit", () => {
context("when already deposit proxy token in fair launch")

2021-11-11 05:57 UTC, alpanaca commented on tests/AlpacaFeeder.test.ts
> +      it("should revert if we already deposit proxy token in fair launch", async () => {
it("should revert")

2021-11-11 05:57 UTC, alpanaca commented on tests/AlpacaFeeder.test.ts
> +      it("should revert if who is not owner try deposit", async () => {
context first, then it

2021-11-11 06:03 UTC, ricardo-alpaca commented on contracts/8.7/AlpacaFeeder.sol
> +    ReentrancyGuardUpgradeable.__ReentrancyGuard_init();
You declared `ReentrancyGuardUpgradeable` here, but there is no where in the code that use `nonReentrant` modifier.

2021-11-11 06:07 UTC, ricardo-alpaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +contract MockProxyToken is IProxyToken, ERC20Upgradeable, OwnableUpgradeable {
Is this really just a mock? Because I could not find the actual implementation for `ProxyToken`. Will we deploy this contract as the Proxy Token?

2021-11-11 06:09 UTC, sora-alpaca commented on contracts/8.7/mocks/MockProxyToken.sol
> +contract MockProxyToken is IProxyToken, ERC20Upgradeable, OwnableUpgradeable {
it's just a mock from DebtToken krub

2021-11-11 10:52 UTC, alpanaca approved these changes

2021-11-12 09:03 UTC, jr-alpaca commented on contracts/8.7/AlpacaFeeder.sol
> +    emit LogFeedGrassHouse(token.myBalance());
this line will always emit 0 since it already feed to GrassHouse

2021-11-15 05:07 UTC, jr-alpaca approved these changes

2021-11-15 13:53 UTC, spicysquid168 commented on contracts/8.7/AlpacaFeeder.sol
> +    token.safeApprove(address(grassHouse), 0);
No need this. As ALPACA token will decrease `_feedAmount` allowance

2021-11-15 13:53 UTC, spicysquid168 commented on contracts/8.7/interfaces/IBEP20.sol
> +  function safeTransfer(address _to, uint256 _amount) external;
`safeTransfer` is not part of BEP20, so remove it please.

2021-11-15 13:53 UTC, spicysquid168 commented on tests/AlpacaFeeder.test.ts
> +  const fairLuancePoolId = 123;
`FAIR_LAUNCH_POOL_ID`

2021-11-15 13:53 UTC, spicysquid168 commented on tests/AlpacaFeeder.test.ts
> +    const MOCKPROXYTOKEN = (await ethers.getContractFactory("MockProxyToken", deployer)) as MockProxyToken__factory;
MockProxyToken

2021-11-15 13:53 UTC, spicysquid168 commented on tests/AlpacaFeeder.test.ts
> +    const MOCKFAIRLAUNCH = (await ethers.getContractFactory("MockFairLaunch", deployer)) as MockFairLaunch__factory;
MockFairLaunch

2021-11-15 13:53 UTC, spicysquid168 commented on tests/AlpacaFeeder.test.ts
> +    const MOCKGRASSHOUSE = (await ethers.getContractFactory("MockGrassHouse", deployer)) as MockGrassHouse__factory;
MockGrassHouse

2021-11-15 13:53 UTC, spicysquid168 commented on tests/AlpacaFeeder.test.ts
> +    const ALCAPAFEEDER = (await ethers.getContractFactory("AlpacaFeeder", deployer)) as AlpacaFeeder__factory;
AlpacaFeeder

2021-11-17 06:40 UTC, merged